# ===============================
# Application
# ===============================

spring.application.name=banking-backend


# ===============================
# Server
# ===============================

server.port=${SERVER_PORT:8080}


# ===============================
# PostgreSQL Database
# ===============================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bankdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Sachin1301#}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# Logging
# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# ===============================
# Jackson
# ===============================

spring.jackson.serialization.fail-on-empty-beans=false


# ===============================
# Error Response
# ===============================

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never


# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET:ChangeThisToAVeryLongRandomSecretKeyOfAtLeast32BytesForHS256}
jwt.expiration-ms=86400000


# ===============================
# Admin Bootstrap
# ===============================

admin.bootstrap.enabled=true
admin.default.email=${ADMIN_EMAIL:sach34861301@gmail.com}
admin.default.password=${ADMIN_PASSWORD:Sachin1301#}


# ===============================
# React Frontend / CORS
# ===============================

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}


# ===============================
# Resend Email API
# ===============================

resend.api-key=${RESEND_API_KEY}

# For initial Resend testing
resend.from-email=onboarding@resend.dev
resend.from-name=Banking System


# ===============================
# Transaction OTP
# ===============================

otp.expiration-minutes=5
otp.max-attempts=5
otp.resend-cooldown-seconds=30


# ===============================
# Cookie Security
# ===============================

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict