import { useEffect, useMemo, useState } from "react";
import { accountsApi, usersApi } from "../../api/services";
import { LedgerTable, StatusPill } from "../../components/Ledger";
import { money } from "../../utils/format";

export default function AccountManagement(){
 const[accounts,setAccounts]=useState([]);const[users,setUsers]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[search,setSearch]=useState("");const[showForm,setShowForm]=useState(false);const[saving,setSaving]=useState(false);
 const[form,setForm]=useState({userId:"",accountHolderName:"",accountType:"SAVINGS",balance:"0"});
 const load=async()=>{setLoading(true);try{const[a,u]=await Promise.all([accountsApi.listAll(),usersApi.listAll()]);setAccounts(a);setUsers(u.filter(x=>x.role!=="ADMIN"));setError("");}catch(e){setError(e.response?.data?.message||"Could not load accounts.");}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const selectUser=(id)=>{const u=users.find(x=>String(x.id)===String(id));setForm(f=>({...f,userId:id,accountHolderName:u?.fullName||""}));};
 const open=async(e)=>{e.preventDefault();setSaving(true);try{await accountsApi.open({...form,userId:Number(form.userId),balance:Number(form.balance)});setShowForm(false);setForm({userId:"",accountHolderName:"",accountType:"SAVINGS",balance:"0"});await load();}catch(e2){setError(e2.response?.data?.message||"Could not open account.");}finally{setSaving(false);}};
 const close=async(id)=>{if(!window.confirm("Close this account? Transactions remain in history."))return;try{await accountsApi.close(id);await load();}catch(e){setError(e.response?.data?.message||"Could not close account.");}};
 const rows=useMemo(()=>accounts.filter(a=>!search.trim()||[a.accountNumber,a.accountHolderName,a.accountType].some(v=>v?.toLowerCase().includes(search.toLowerCase()))),[accounts,search]);
 const columns=[{key:"accountNumber",label:"Account",render:r=><div><p className="font-mono font-bold text-slate-800">{r.accountNumber}</p><p className="text-xs text-slate-400 mt-1">User #{r.userId}</p></div>},{key:"accountHolderName",label:"Account holder",render:r=><p className="font-semibold">{r.accountHolderName}</p>},{key:"accountType",label:"Type"},{key:"balance",label:"Balance",render:r=><span className="font-extrabold">{money(r.balance)}</span>,sortValue:r=>Number(r.balance||0)},{key:"active",label:"Status",render:r=><StatusPill status={r.active?"ACTIVE":"CLOSED"}/>},{key:"actions",label:"Actions",render:r=>r.active?<button onClick={()=>close(r.id)} className="text-xs font-bold text-red-600 hover:underline">Close account</button>:<span className="text-xs text-slate-400">Closed</span>}];
 return <div className="space-y-5">{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700 text-sm font-semibold">{error}</div>}
 <div className="bank-surface p-4 flex flex-wrap items-center justify-between gap-3"><input className="form-input !w-auto min-w-72" placeholder="Search account or holder…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary-btn !py-2.5 !px-4" onClick={()=>setShowForm(v=>!v)}>{showForm?"Cancel":"+ Open new account"}</button></div>
 {showForm&&<form onSubmit={open} className="bank-surface p-6 grid sm:grid-cols-2 xl:grid-cols-4 gap-4 items-end"><div><label className="form-label">Customer</label><select className="form-input" required value={form.userId} onChange={e=>selectUser(e.target.value)}><option value="">Select customer</option>{users.map(u=><option key={u.id} value={u.id}>{u.fullName} · {u.email}</option>)}</select></div><div><label className="form-label">Account holder</label><input className="form-input" required value={form.accountHolderName} onChange={e=>setForm(f=>({...f,accountHolderName:e.target.value}))}/></div><div><label className="form-label">Account type</label><select className="form-input" value={form.accountType} onChange={e=>setForm(f=>({...f,accountType:e.target.value}))}><option>SAVINGS</option><option>CURRENT</option></select></div><div><label className="form-label">Opening balance</label><input className="form-input" type="number" min="0" step="0.01" required value={form.balance} onChange={e=>setForm(f=>({...f,balance:e.target.value}))}/></div><div className="sm:col-span-2 xl:col-span-4 flex justify-end"><button className="primary-btn min-w-44" disabled={saving}>{saving?"Opening…":"Open account"}</button></div></form>}
 {loading?<div className="bank-surface p-8 text-slate-500">Loading accounts…</div>:<LedgerTable columns={columns} rows={rows} keyField="id"/>}</div>;
}
