import { useEffect, useMemo, useState } from "react";
import { transactionsApi } from "../../api/services";
import { LedgerTable, StatusPill } from "../../components/Ledger";
import ExportBar from "../../components/ExportBar";
import DateRangeFilter from "../../components/DateRangeFilter";
import { money, dateTime, transactionLabel } from "../../utils/format";

export default function AllTransactions(){
 const[transactions,setTransactions]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[search,setSearch]=useState("");const[type,setType]=useState("ALL");const[from,setFrom]=useState("");const[to,setTo]=useState("");
 useEffect(()=>{transactionsApi.listAll().then(setTransactions).catch(e=>setError(e.response?.data?.message||"Could not load transactions.")).finally(()=>setLoading(false));},[]);
 const filtered=useMemo(()=>transactions.filter(t=>{if(type!=="ALL"&&t.transactionType!==type)return false;const q=search.trim().toLowerCase();if(q&&![t.accountNumber,t.counterpartyAccountNumber,t.referenceId,t.transactionType,t.status].some(v=>v?.toLowerCase().includes(q)))return false;if(from&&new Date(t.createdAt)<new Date(from))return false;if(to){const d=new Date(to);d.setHours(23,59,59,999);if(new Date(t.createdAt)>d)return false;}return true;}),[transactions,search,type,from,to]);
 const columns=[{key:"createdAt",label:"Date & time",render:r=><div><p className="font-semibold">{dateTime(r.createdAt)}</p><p className="text-xs text-slate-400 mt-1">{r.referenceId||`TX-${r.id}`}</p></div>,exportValue:r=>dateTime(r.createdAt)},{key:"accountNumber",label:"Account"},{key:"transactionType",label:"Type",render:r=><div><p className="font-semibold">{transactionLabel(r.transactionType)}</p>{r.counterpartyAccountNumber&&<p className="text-xs text-slate-400 mt-1">Counterparty: {r.counterpartyAccountNumber}</p>}</div>},{key:"amount",label:"Amount",render:r=><span className="font-extrabold">{money(r.amount)}</span>,sortValue:r=>r.amount,exportValue:r=>r.amount},{key:"balanceAfter",label:"Balance after",render:r=>money(r.balanceAfter),exportValue:r=>r.balanceAfter},{key:"status",label:"Status",render:r=><StatusPill status={r.status}/>,exportValue:r=>r.status}];
 return <div className="space-y-5">{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700 text-sm font-semibold">{error}</div>}<div className="bank-surface p-4 flex flex-wrap gap-3 items-center"><input className="form-input !w-auto min-w-64 flex-1" placeholder="Search account, reference or counterparty…" value={search} onChange={e=>setSearch(e.target.value)}/><select className="form-input !w-auto" value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All types</option><option value="DEPOSIT">Deposit</option><option value="WITHDRAW">Withdrawal</option><option value="TRANSFER_OUT">Transfer sent</option><option value="TRANSFER_IN">Transfer received</option></select><DateRangeFilter from={from} to={to} onFrom={setFrom} onTo={setTo} onClear={()=>{setFrom("");setTo("")}}/><ExportBar title="Bank Transaction Ledger" filename="all-transactions" columns={columns} rows={filtered}/></div>{loading?<div className="bank-surface p-8 text-slate-500">Loading transactions…</div>:<LedgerTable columns={columns} rows={filtered} keyField="id"/>}</div>;
}
